### ISSUE TITLE
App not building on toolchain 46.0 f7

### ISSUE THREAD

**Issue by doomwastaken** [0xchocolate/flipperzero-esp-flasher#12]
Greetings! I am from Flipper Devices team and would like to say thank you for submitting your app to the catalog. We are finalizing API prior to 1.0 release and currently your application cannot be built for latest toolchain. Currently we are testing 0.95.0-rc and app is not being built for that version. 

We are currently working on automating the messages from our build server, so this one is manual :)

If you have any questions, just tag me

**Comment by 0xchocolate** [comment]
Hi, I think I just need to get rid of two calls to pdMS_TO_TICKS. I noticed in the API change that calls to this were simply removed (meaning tick = 1ms), so I'll try that and test.
