### ISSUE TITLE
Invalid chip ID error.

### ISSUE THREAD

**Issue by Scottyp1980** [0xchocolate/flipperzero-esp-flasher#16]
I am using the flipper zero wifi dev board esp32, I am getting all the way through the flash and then at the end it tells me In valid chip ID Boot loader for wrong chip? Can anyone tell me what I am dealing with?

**Comment by 0xchocolate** [comment]
Which bin(s) did you flash?

**Comment by Scottyp1980** [comment]
esp32_marauder.ino.bootloader_2.bin, esp32_marauder.ino.partitions.bin, and esp32_marauder_v0_13_6_20231214_esp32_lddb.bin  which I renamed firmware in the flipper.

**Comment by Scottyp1980** [comment]
when you posed that last question i decided to take a closer look at my bin files and had realized i didnt download the ones for the flipper wifi dev.  I am new to this and have been working on this for three days, none of the other methods seemed to work.  thank you.

**Comment by Scottyp1980** [comment]
if i switch to roguemaster will marauder still work?
