### ISSUE TITLE
adding evil portal

### ISSUE THREAD

**Issue by Scottyp1980** [0xchocolate/flipperzero-esp-flasher#18]
Is there any other route for me to flash evil portal onto my flipper zero wifi dev board without using  flipC.org which is down  at the moment.  Ive succesfully flashed esp32 marauder with the ESPflasher, but i am stuck at this point.  Still new to this.

**Comment by 0xchocolate** [comment]
What are you trying to do? Just use Marauder's builtin Evil Portal.

flipc.org is irrelevant

**Comment by Scottyp1980** [comment]
Thats what I thought, but every time i try to use it built in with the marauder that I flashed using espflasher it doesnt seem to work. Does it make a difference if im running unleashed firmware?  Im going to try it again to see if i missed something.

**Comment by Scottyp1980** [comment]
Ah, I was not configuring the SSID properly!  Works great! thank you for taking the time to respond and creating such a great tool.
