### ISSUE TITLE
Можно ли и как прошить esp8266 D1 Mini или ESP 12

### ISSUE THREAD

**Issue by Hm7284156** [0xchocolate/flipperzero-esp-flasher#3]
Можно ли и как прошить esp8266 D1 Mini или ESP 12

**Comment by 0xchocolate** [comment]
Yes, ESP8266 should be supported by the library, though it hasn't been tested. Which fw/bin are you trying to flash?

**Comment by Hm7284156** [comment]
Wifi_Scanner.bin не выходит, как только не пытался

**Comment by Hm7284156** [comment]
Esp8266_Scanner_wifi.bin

**Comment by 0xchocolate** [comment]
Try selecting the "S3" option first and then for Bootloader (0x0), browse and select your bin. Then flash.
