### ISSUE TITLE
Installation on Unleashed Firmware

### ISSUE THREAD

**Issue by victorkjung** [0xchocolate/flipperzero-esp-flasher#4]
Thank you for all your experiments and guidance. I am a Mac iOS user attempting to load ESP32 firmware update on my Flipper Zero Wifi Dev board. Will this work if I have unleashed firmware installed on my Flipper Zero?

**Comment by 0xchocolate** [comment]
Not sure how "Mac iOS" is relevant. Just download the latest app release for unleashed: https://github.com/0xchocolate/flipperzero-esp-flasher/actions/runs/5838644792

**Comment by victorkjung** [comment]
Thanks @0xchocolate ..... you make the FlipperZero lifestyle so easy.
